<tr id="row_magepsycho_disableregistration_restriction_setting">
    <td colspan="5">
        <div class="section-config">
            <div class="entry-edit-head admin__collapsible-block">
                <?= /* @noEscape */ __('If you need the complete restriction functionality for your store in different ways (disabling registration, requiring customer approval, restricting access to special customers while allowing guest access to certain pages), please visit') ?>
                <a href="https://www.magepsycho.com/magento-2-store-restriction-pro.html?utm_source=extension-setting&utm_medium=banner&utm_campaign=m2-disable-registration" target="_blank" title="Magento 2 Store Restriction Pro">
                    <?= /* @noEscape */ __('Magento 2 Store Restriction Pro') ?>
                </a>
            </div>
        </div>
    </td>
</tr>
